In [4]:
import numpy as np
weight = [2,3,4,5]
profit = [1,2,5,6]
n = 4
w = 8

In [7]:
profit_matrix = np.zeros((n+1,w+1))

def calculate_profit(weight, profit, i, w):

    # i => row ,   j (w) => column

    if i==0 or w<=0:         # 1st row is always one
        return 0
    
    if weight[i-1]>w:        # if weight exceeds bag capacity
        return profit_matrix[i-1][w]
    
    # profit w/o current object
    t2 = profit_matrix[i-1][w]   
    
    # profit with current object
    t1 = profit_matrix[i-1][w-weight[i-1]] + profit[i-1]

    return max(t1,t2)


# loop over to calculate all possibilities for profit
for i in range(1, n+1):
    for j in range(1, w+1):
        profit_matrix[i][j] = calculate_profit(weight, profit, i, j)

    print(f"Row{i}  (considering {i} items) : ", profit_matrix[i])

Row1  (considering 1 items) :  [0. 0. 1. 1. 1. 1. 1. 1. 1.]
Row2  (considering 2 items) :  [0. 0. 1. 2. 2. 3. 3. 3. 3.]
Row3  (considering 3 items) :  [0. 0. 1. 2. 5. 5. 6. 7. 7.]
Row4  (considering 4 items) :  [0. 0. 1. 2. 5. 6. 6. 7. 8.]


In [8]:
def find_selected_items_for_max_profit(profit_matrix, weight, profit, n, w):
    selected_items = []
    current_w = w
    for i in range(n, 0, -1):
        if profit_matrix[i][current_w] != profit_matrix[i-1][current_w]:
            selected_items.append(i-1)
            current_w -= weight[i-1]
    return selected_items


selected = find_selected_items_for_max_profit(profit_matrix, weight, profit, n, w)
print("\nFinal profit matrix:")
print(profit_matrix)
print(f"\nMaximum profit: {profit_matrix[n][w]}")
print(selected)


Final profit matrix:
[[0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 1. 1. 1. 1. 1. 1. 1.]
 [0. 0. 1. 2. 2. 3. 3. 3. 3.]
 [0. 0. 1. 2. 5. 5. 6. 7. 7.]
 [0. 0. 1. 2. 5. 6. 6. 7. 8.]]

Maximum profit: 8.0
[3, 1]
